export enum WeaponType {
    Dagger,
    Fist,
    OneHandedAxe,
    OneHandedMace,
    OneHandedSword,
    Warglaive,

    Polearm,
    Stave,
    TwoHandedAxe,
    TwoHandedMace,
    TwoHandedSword,

    Bow,
    Crossbow,
    Gun,
    Thrown,
    Wand,

    FishingPole,

    // For filtering purposes
    OffHand,
    OffHandIntellect,
    Shield,

    DaggerAgility = 200,
    DaggerIntellect,
    OneHandedAxeAgility,
    OneHandedAxeStrength,
    OneHandedMaceAgility,
    OneHandedMaceIntellect,
    OneHandedMaceStrength,
    OneHandedSwordAgility,
    OneHandedSwordIntellect,
    OneHandedSwordStrength,
    PolearmAgility,
    //TwoHandedAxe,
    //TwoHandedAxe,
    TwoHandedAxeStrength,
    //TwoHandedMace,
    //TwoHandedMace,
    TwoHandedMaceStrength,
    //TwoHandedSword,
    //TwoHandedSword,
    TwoHandedSwordStrength,
    StaveAgility,
    StaveIntellect,
}
