export enum WeaponType {
    Dagger,
    Fist,
    OneHandedAxe,
    OneHandedMace,
    OneHandedSword,
    Warglaive,

    Polearm,
    Stave,
    TwoHandedAxe,
    TwoHandedMace,
    TwoHandedSword,

    Bow,
    Crossbow,
    Gun,
    Thrown,
    Wand,

    FishingPole,

    // For filtering purposes
    OffHand,
    OffHandIntellect,
    Shield,
    ShieldIntellect,
    ShieldStrength,

    DaggerAgility = 200,
    DaggerIntellect,
    FistAgility,
    FistIntellect,
    OneHandedAxeAgility,
    OneHandedAxeIntellect,
    OneHandedAxeStrength,
    OneHandedMaceAgility,
    OneHandedMaceIntellect,
    OneHandedMaceStrength,
    OneHandedSwordAgility,
    OneHandedSwordIntellect,
    OneHandedSwordStrength,
    PolearmAgility,
    PolearmIntellect,
    PolearmStrength,
    TwoHandedAxeAgility,
    TwoHandedAxeIntellect,
    TwoHandedAxeStrength,
    TwoHandedMaceAgility,
    TwoHandedMaceIntellect,
    TwoHandedMaceStrength,
    TwoHandedSwordAgility,
    TwoHandedSwordIntellect,
    TwoHandedSwordStrength,
    StaveAgility,
    StaveIntellect,
    StaveStrength,
}
