version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/development.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BattleNet__ClientID: $BattleNet__ClientID
      BattleNet__ClientSecret: $BattleNet__ClientSecret
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - wowthing
    volumes:
      - ./:/app/
      - /app/apps/backend/bin/container/
      - /app/apps/backend/obj/container/

  web:
    build:
      context: .
      dockerfile: apps/web/development.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BattleNet__ClientID: $BattleNet__ClientID
      BattleNet__ClientSecret: $BattleNet__ClientSecret
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - wowthing
    ports:
      - "55500:5000"
      - "55501:5001"
    volumes:
      - ./:/app/
      - /app/apps/web/bin/container/
      - /app/apps/web/obj/container/

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/development.Dockerfile
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - wowthing
    ports:
      - "55505:55505"
    volumes:
      - ./:/app/
      - frontend-cache:/root/.npm
      - frontend-nm:/app/node_modules/

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: wowthing
    networks:
      - wowthing
    ports:
      - "55532:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - wowthing
    ports:
      - "55579:6379"
    restart: always
    volumes:
      - redis:/data

networks:
  wowthing:

volumes:
  frontend-cache:
  frontend-nm:
  postgres:
  redis:
