export enum Holiday {
    Anniversary,
    Brewfest,
    ChildrensWeek,
    DarkmoonFaire,
    HallowsEnd,
    LoveIsInTheAir,
    LunarFestival,
    MidsummerFireFestival,
    Noblegarden,
    PilgrimsBounty,
    TrialOfStyle,
    WinterVeil,

    BonusArenaSkirmish,
    BonusBattleground,
    BonusDelve,
    BonusDungeon,
    BonusPetBattle,
    BonusWorldQuest,

    TimewalkingClassic,
    TimewalkingTbc,
    TimewalkingWotlk,
    TimewalkingCata,
    TimewalkingMop,
    TimewalkingWod,
    TimewalkingLegion,
    TimewalkingBfa,

    BrawlArathiBlizzard = 1000,
    BrawlClassicAshran,
    BrawlCompStomp,
    BrawlCookingImpossible,
    BrawlDeepSix,
    BrawlDeepwindDunk,
    BrawlGravityLapse,
    BrawlPackedHouse,
    BrawlShadoPanShowdown,
    BrawlSouthshoreVsTarrenMill,
    BrawlTempleOfHotmogu,
    BrawlWarsongScramble,
}

export const timewalkingHolidays = [
    Holiday.TimewalkingClassic,
    Holiday.TimewalkingTbc,
    Holiday.TimewalkingWotlk,
    Holiday.TimewalkingCata,
    Holiday.TimewalkingMop,
    Holiday.TimewalkingWod,
    Holiday.TimewalkingLegion,
    Holiday.TimewalkingBfa,
];
