namespace Wowthing.Lib.Enums;

public enum StringType : short
{
    WowItemName = 1,
    WowMountName = 2,
    WowCreatureName = 3,
    WowJournalTierName = 4,
    WowJournalInstanceName = 5,
    WowJournalEncounterName = 6,
    WowSoulbindName = 7,
    WowSkillLineName = 8,
    WowCharacterSpecializationName = 9,
    WowCharacterClassName = 10,
    WowCharacterRaceName = 11,
    WowCurrencyName = 12,
    WowCurrencyCategoryName = 13,
    WowReputationName = 14,
    WowReputationDescription = 15,
    WowSpellItemEnchantmentName = 16,
    WowQuestName = 17,
    WowHolidayName = 18,
    WowHolidayDescription = 19,
    WowKeystoneAffixName = 20,
    WowCharacterTitle = 21,
    WowReputationTier = 22,
    WowInventorySlot = 23,
    WowInventoryType = 24,
    WowTransmogSetGroupName = 25,
    WowTransmogSetName = 26,
    WowSharedString = 27,
    WowSpellName = 28,
    WowExpansion = 29,
    WowCampaignName = 30,
    WowQuestLineName = 31,
    WowCurrencyDescription = 32,
    WowChallengeDungeonName = 33,
    WowDecorCategoryName = 34,
    WowDecorSubcategoryName = 35,
    WowDecorObjectName = 36,

    // Hacky garbage
    WowJournalInstanceMapName = 1000,
}
