// Armor
export { default as gameBarbute } from '@iconify/icons-game-icons/barbute'
export { default as gameBeltArmor } from '@iconify/icons-game-icons/belt-armor'
export { default as gameBigDiamondRing } from '@iconify/icons-game-icons/big-diamond-ring'
export { default as gameBracer } from '@iconify/icons-game-icons/bracer'
export { default as gameChestArmor } from '@iconify/icons-game-icons/chest-armor'
export { default as gameDorsalScales } from '@iconify/icons-game-icons/dorsal-scales'
export { default as gameGauntlet } from '@iconify/icons-game-icons/gauntlet'
export { default as gameGreaves } from '@iconify/icons-game-icons/greaves'
export { default as gameHeartNecklace } from '@iconify/icons-game-icons/heart-necklace'
export { default as gameMetalBoot } from '@iconify/icons-game-icons/metal-boot'
export { default as gameShirt } from '@iconify/icons-game-icons/shirt'

// Misc items
export { default as gameBackpack } from '@iconify/icons-game-icons/backpack'

// Weapons
export { default as gameBatLeth } from '@iconify/icons-game-icons/bat-leth'
export { default as gameBattleAxe } from '@iconify/icons-game-icons/battle-axe'
export { default as gameBlunderbuss } from '@iconify/icons-game-icons/blunderbuss'
export { default as gameBrassKnuckles } from '@iconify/icons-game-icons/brass-knuckles'
export { default as gameBroadsword } from '@iconify/icons-game-icons/broadsword'
export { default as gameCape } from '@iconify/icons-game-icons/cape'
export { default as gameCrossbow } from '@iconify/icons-game-icons/crossbow'
export { default as gameCurvyKnife } from '@iconify/icons-game-icons/curvy-knife'
export { default as gameFairyWand } from '@iconify/icons-game-icons/fairy-wand'
export { default as gameGladius } from '@iconify/icons-game-icons/gladius'
export { default as gameHatchet } from '@iconify/icons-game-icons/hatchet'
export { default as gamePocketBow } from '@iconify/icons-game-icons/pocket-bow'
export { default as gameSecretBook } from '@iconify/icons-game-icons/secret-book'
export { default as gameShield } from '@iconify/icons-game-icons/shield'
export { default as gameThorHammer } from '@iconify/icons-game-icons/thor-hammer'
export { default as gameTrident } from '@iconify/icons-game-icons/trident'
export { default as gameWizardStaff } from '@iconify/icons-game-icons/wizard-staff'
export { default as gameWoodClub } from '@iconify/icons-game-icons/wood-club'
